### ISSUE TITLE
migrate to ruaml.yaml

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#109]
Looks like pyyaml is pretty much abandoned. We should migrate to ruaml.yaml (AnsibleInventory) is already using it.

**Comment by ktbyers** [comment]
I don't have any issues with this.

**Comment by ogenstad** [comment]
I was going to swap out Pyyaml to ruaml.yaml but had a thought regarding how we read the files.

Say we have a broken yaml file like the one below:

```yaml
---
host1.cmh:
    site: cmh
    role: host
    group: cmh-host
    nos: linux

host2.cmh:
    site: cmh
    role host
    group: cmh-host
    nos: linux
```

We can read this file in two ways:

```python
import ruamel.yaml

host_file = '/Users/patrick/src/playground/brigade-tests/demo/broken_hosts.yaml'


with open(host_file, "r") as f:
    yml = ruamel.yaml.YAML(typ="rt", pure=True)
    data = yml.load(f.read())


with open(host_file, "r") as f:
    yml = ruamel.yaml.YAML(typ="rt", pure=True)
    data = yml.load(f)
```

In the first example we will successfully read the file and return the contents, but the parser will fail:
```python
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/main.py", line 266, in load
    return constructor.get_single_data()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 106, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 580, in parse_block_mapping_value
    if not self.scanner.check_token(KeyToken):
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1618, in check_token
    while self.need_more_tokens():
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 196, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 345, in stale_possible_simple_keys
    "could not find expected ':'", self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 10, column 5:
        role host
        ^ (line: 10)
could not find expected ':'
  in "<unicode string>", line 11, column 5:
        group: cmh-host
        ^ (line: 11)
```

With the second action the failure lets us see which file had the error:

```python
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/main.py", line 266, in load
    return constructor.get_single_data()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 106, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 580, in parse_block_mapping_value
    if not self.scanner.check_token(KeyToken):
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1618, in check_token
    while self.need_more_tokens():
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 196, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/Users/patrick/.virtualenvs/brigade/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 345, in stale_possible_simple_keys
    "could not find expected ':'", self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "/Users/patrick/src/playground/brigade-tests/demo/broken_hosts.yaml", line 10, column 5
could not find expected ':'
  in "/Users/patrick/src/playground/brigade-tests/demo/broken_hosts.yaml", line 11, column 5
>>>
```

The first example provides a bit more context with the content since we see that `role host` is what caused the error. In the second example, we do however get the actual file that failed along with the line number where the failure occurred. I think the second example will be easier for users to troubleshoot. 

What are your thoughts?

**Comment by dbarrosop** [comment]
I'd do the first one. We can also use the logging to log the file being read and the error.

**Comment by ktbyers** [comment]
I like one better, but would vote we catch the exception and re-raise it with the name of the file that was being read.
