### ISSUE TITLE
Exception doesn't exist for self defined failures

### ISSUE THREAD

**Issue by ogenstad** [nornir-automation/nornir#129]
This code causes an error for self-inflicted failures.
https://github.com/brigade-automation/brigade/blob/develop/brigade/core/task.py#L96-L98

For example:
```python
def echo_task(task, msg):
    failed = False
    if msg == "5":
            failed = True
    return Result(host=task.host, result=f"Hello from Brigade: {msg}", failed=failed)


def data_with_greeting(task):
    task.run(task=echo_task, name="First", msg='1')
    task.run(task=echo_task, name="Second", msg='5')
    task.run(task=echo_task, name="Third", msg='3')
    task.run(task=echo_task, name="Fourth", msg='4', severity=logging.DEBUG)
    task.run(task=echo_task, name="Fifth", msg='5', severity=logging.DEBUG)

Traceback (most recent call last):
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 61, in start
    r = self.task(self, **self.params)
  File "test-run.py", line 32, in data_with_greeting
    task.run(task=echo_task, name="Second", msg='5')
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 98, in run
    raise r.exception
TypeError: exceptions must derive from BaseException
```
The Result.exception is set to None by default and doesn't get changed when a failed task doesn't throw an error.
https://github.com/brigade-automation/brigade/blob/develop/brigade/core/task.py#L58-L67

```python
        if r.failed:
            # Without this we will keep running the grouped task
            raise r.exception
```
Either we need to check if r.exception=None, and raise some other generic Exception. Or we can let users return a failure reason. 

Thoughts?

**Comment by dbarrosop** [comment]
I'd say that shouldn't be allowed (maybe we need to rename the argument to `_failed` to make it clearer). If the task is unable to do what was supposed to do the task should raise an Exception.

**Comment by dbarrosop** [comment]
no, I don't think it was. Maybe it surfaced the problem but I don't think tasks should return failed. Maybe we should revisit this and make sure certain fields that are supposed to be filled by brigade core itself (and not by a plugin) is properly marked as private with prepending `_`.

I will leave this issue open for that particular purpose :D

**Comment by ogenstad** [comment]
Just to illustrate what I meant, if we have a file which looks like this:

```python
from brigade.core import InitBrigade
from brigade.plugins.functions.text import print_result
from brigade.core.task import Result


brg = InitBrigade(
    raise_on_error=False)


def fail_on_me(task):
    return Result(host=task.host, result="single", failed=True)


def sub_task(task):
    task.run(task=fail_on_me)
    return Result(host=task.host, result="grouped_task")


result = brg.run(fail_on_me)
print_result(result)
```
Running this will produce this output:

```
fail_on_me**********************************************************************
* srv1 ** changed : False ******************************************************
vvvv fail_on_me ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
single
^^^^ END fail_on_me ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* srv2 ** changed : False ******************************************************
vvvv fail_on_me ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
single
^^^^ END fail_on_me ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If I change the run to this:
```
result = brg.run(sub_task)
```

I instead get this output:

```
sub_task************************************************************************
* srv1 ** changed : False ******************************************************
vvvv sub_task ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 61, in start
    r = self.task(self, **self.params)
  File "will-fail.py", line 15, in sub_task
    task.run(task=fail_on_me)
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 98, in run
    raise r.exception
TypeError: exceptions must derive from BaseException

^^^^ END sub_task ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* srv2 ** changed : False ******************************************************
vvvv sub_task ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 61, in start
    r = self.task(self, **self.params)
  File "will-fail.py", line 15, in sub_task
    task.run(task=fail_on_me)
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 98, in run
    raise r.exception
TypeError: exceptions must derive from BaseException

^^^^ END sub_task ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

With that in mind I think it makes sense to mark the failed property as private.

**Comment by ogenstad** [comment]
Should we keep this open, after #131 was merged it isn't really an issue. Or should we rename failed to _failed?

**Comment by dbarrosop** [comment]
I think we can close it for now :)
