### ISSUE TITLE
NSOT inventory: more robust handling ids in sites, devices and interfaces

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#184]
Enhancement request
Current implementation assumes that the order of the returned objects from NSOT rest API corresponds to IDs.  
For example, here is the data:
```
[
  {
    "id": 1,
    "name": "site1",
    "description": ""
  },
  {
    "id": 2,
    "name": "site2",
    "description": ""
  }
]
```
and here is the code in `nornir.plugins.inventory.nsot`:
```
        for d in devices:
            d["site"] = sites[d["site_id"] - 1]["name"]
...
        for i in interfaces:
            devices[i["device"] - 1]["interfaces"][i["name"]] = i
```
It relies on the order of the returned items. I am pretty sure it will break if sites/interfaces/devices are deleted.

**Comment by Lewis-Goulden** [comment]
I have stumbeld on this issue, I had created multiple sites in NSOT and deleted them. 

I then had problems.

After rebuilding new NSOT container the issue has now disappeard. 

Error: 
`(nornir_testing) bash-3.2$ python run.py 
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    nr = InitNornir(config_file="nsot_inventory.yaml")
  File "/Users/lgoulden280/.local/share/virtualenvs/nornir_testing-r41UUUR9/lib/python3.7/site-packages/nornir/init_nornir.py", line 77, in InitNornir
    **conf.inventory.options,
  File "/Users/lgoulden280/.local/share/virtualenvs/nornir_testing-r41UUUR9/lib/python3.7/site-packages/nornir/core/deserializer/inventory.py", line 129, in deserialize
    deserialized = cls(*args, **kwargs)
  File "/Users/lgoulden280/.local/share/virtualenvs/nornir_testing-r41UUUR9/lib/python3.7/site-packages/nornir/plugins/inventory/nsot.py", line 69, in __init__
    d["data"] = {"site": sites[d["site_id"] - 1]["name"], "interfaces": {}}
IndexError: list index out of range`

**Comment by ktbyers** [comment]
Closing...plugin issue and old.
