### ISSUE TITLE
Please ensure you pass the 'secret' argument to ConnectHandler

### ISSUE THREAD

**Issue by qL555** [nornir-automation/nornir#253]
Hey!
I recently tried to get into nornir. In the past I already used the netmiko/paramiko libaries.

If I try to execute the following example code:
```
from nornir.core import InitNornir
from nornir.plugins.tasks.networking import napalm_get
from nornir.plugins.functions.text import print_result

nr = InitNornir()

result = nr.run(
             napalm_get,
             getters=['get_facts'])

print_result(result)
```

I get the following outcome:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 683, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 160, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 442, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 685, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1219, in enable
    output += self.read_until_prompt()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 510, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 450, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.5/dist-packages/nornir/plugins/tasks/networking/napalm_get.py", line 41, in napalm_get
    device = task.host.get_connection("napalm")
  File "/usr/local/lib/python3.5/dist-packages/nornir/core/inventory.py", line 250, in get_connection
    raise r[self.name].exception
  File "/usr/local/lib/python3.5/dist-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.5/dist-packages/nornir/plugins/tasks/connections/napalm_connection.py", line 53, in napalm_connection
    host.connections["napalm"].open()
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 138, in open
    netmiko_optional_args=self.netmiko_optional_args,
  File "/usr/local/lib/python3.5/dist-packages/napalm/base/base.py", line 87, in _netmiko_open
    self._netmiko_device.enable()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 18, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1221, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.

```
My questions is how can I set the 'secert' agrument in nornir?

best regards
Kevin

**Comment by rchimborazo** [comment]
Hi there, you could try add napalm_options: {'secret': 'my_secret_pass'}  at
hosts (host level) or groups (group level) yaml files:

E.g.  (hosts.yaml)

---router.site1:
  nornir_host: <ip_address>
  groups: ['your_group']
  napalm_options: {'secret': 'the_secret_pass'}


KR,

Roberto
