### ISSUE TITLE
Warning about defaults.yaml and then exception if you create an empty file (using config_continue branch)

### ISSUE THREAD

**Issue by ktbyers** [nornir-automation/nornir#258]
Not directly this PR, but we probably should fix this:

Warns about no defaults.yaml.

```
WARNING:root:defaults.yaml: doesn't exist
```

But then if you make an empty file your program crashes:

```
$ touch defaults.yaml
$ python netmiko_simple.py 
Traceback (most recent call last):
  File "netmiko_simple.py", line 24, in <module>
    main()
  File "netmiko_simple.py", line 11, in main
    norn = InitNornir(config_file="./nornir.yml")
  File "/home/kbyers/nornir/nornir/init_nornir.py", line 40, in InitNornir
    **conf.inventory.options
  File "/home/kbyers/nornir/nornir/core/deserializer/inventory.py", line 112, in deserialize
    deserialized = cls(*args, **kwargs)
  File "/home/kbyers/nornir/nornir/plugins/inventory/simple.py", line 39, in __init__
    super().__init__(hosts=hosts, groups=groups, defaults=defaults, *args, **kwargs)
  File "/home/kbyers/VENV/nornir_test/local/lib/python3.6/site-packages/pydantic/main.py", line 166, in __init__
    self.__setstate__(self._process_values(data))
  File "/home/kbyers/VENV/nornir_test/local/lib/python3.6/site-packages/pydantic/main.py", line 328, in _process_values
    return validate_model(self, input_data)
  File "/home/kbyers/VENV/nornir_test/local/lib/python3.6/site-packages/pydantic/main.py", line 504, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
defaults
  value is not a valid dict (type=type_error.dict)
```

My vote is to not warn about 'defaults.yaml' and to also allow an empty defaults.yaml file

**Comment by dbarrosop** [comment]
I referenced a commit that fixes this.

**Comment by dbarrosop** [comment]
Closing this as it's fixed in 2.0.0-beta
