### ISSUE TITLE
Jinja get_source() unimplemented

### ISSUE THREAD

**Issue by TLINDEN** [nornir-automation/nornir#371]
Hello,

I am unable to use jinja template inheritance. The `extends` template command doesn't work and leads to this error:
```
vvvv config_ios ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Subtask: Router Configuration (failed)

---- Router Configuration ** changed : False ----------------------------------- ERROR
Traceback (most recent call last):
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/nornir/plugins/tasks/text/template_file.py", line 35, in template_file
    **kwargs
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/nornir/core/helpers/jinja_helper.py", line 18, in render_from_file
    return t.render(**kwargs)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "templates/asr/router.j2", line 2, in top-level template code
    {% extends "templates/genericrouter.j2" %}
  File "/home/tl/.local/share/virtualenvs/router-gtV0K0m5/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/genericrouter.j2

^^^^ END config_ios ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The template called from the code:
```
{# -*-web-*- #}
{% extends "templates/genericrouter.j2" %}
```

The code:
```python
from nornir import InitNornir
from nornir.plugins.functions.text import print_result as dumper
from nornir.plugins.tasks import networking, text

def config_ios(task):
    r = task.run(task=text.template_file,
                 name="Router Configuration",
                 template="router.j2",
                 path=f"templates/{task.host['hwtype']}")
    print(r.result);

nr = InitNornir(config_file="config.yaml")
routers = nr.filter(site="w81", role="edge")
result = routers.run(task=config_ios)
dumper(result)
```

It doesn't matter, which path I specify for the template, since `jinja2/loaders.py, line 187, get_source` reads (comments removed):
```python
    has_source_access = True
    def get_source(self, environment, template):
        if not self.has_source_access:
            raise RuntimeError('%s cannot provide access to the source' %
                               self.__class__.__name__)
        raise TemplateNotFound(template)
```

Which translates to *always fail unless implemented by the user* (which in this case is nornir).

And the comment of the base class says:
```
class BaseLoader(object):
    """Baseclass for all loaders.  Subclass this and override `get_source` to
    implement a custom loading mechanism.
[..]
```

However, no `get_source`  function is defined anywhere in nornir. Hence the `extends` always fails - or I am doing it wrong.

best regards,
Tom

**Comment by TLINDEN** [comment]
No, my fault. I need to configure all possible template locations, nornir doesn't compute them itself:
```python
    r = task.run(task=text.template_file,
                 name="Router Configuration",
                 template="router.j2",
                 path=(f"templates", f"templates/{task.host['hwtype']}"))
```

(that is, turn the `path` parameter into a list.

**Comment by dbarrosop** [comment]
Glad to see it ended up working out for you. If you think there is something that could be improved (maybe the docs?) let us know, or even better, send a PR :)

**Comment by TLINDEN** [comment]
Well, it would feel more "natural" if nornir generates the path list from the given path. Jinja2 has a function for this, as I've seen. So, my code above could be rewritten as:

```python
from jinja2.loaders import split_template_path

r = task.run(task=text.template_file,
                 name="Router Configuration",
                 template="router.j2",
                 path=split_template_path(f"templates/{task.host['hwtype']}"))
```

which could be done by nornir as well :)

btw - the reason why I need this: I have a top level router config, which is generic for all routers and then some platform specific ones in sub directories and I use the `extend` feature from there.
