### ISSUE TITLE
nornir.core.exceptions.CommandError

### ISSUE THREAD

**Issue by Gobiviswa** [nornir-automation/nornir#412]
Hi, 
I am pretty new to the Nornir. I tried to do sftp using built-in. I am receiving the following error.

code to sftp:
=============================================================================
nr = InitNornir(
    core={"num_workers": 100},
    inventory={
        "plugin": "nornir.plugins.inventory.simple.SimpleInventory",
        "options": {
            "host_file": "hosts.yaml",
            "group_file": "groups.yaml"
        }
    }
)

    leaves_gva = nr.filter(site="ch.gva.dc1", role="leaf")
    r1=leaves_gva.run(files.sftp,action="put",src="/home/ubuntu/nornir/ex.txt",dst="/etc/ex.txt",
                        num_workers=1,)
    print_result(r1)

Error:
=========================================================================

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir/plugins/tasks/files/sftp.py", line 155, in sftp
    files_changed = actions[action](task, scp_client, sftp_client, src, dst, dry_run)
  File "/usr/local/lib/python3.6/site-packages/nornir/plugins/tasks/files/sftp.py", line 120, in put
    changed = compare_put_files(task, sftp_client, src, dst)
  File "/usr/local/lib/python3.6/site-packages/nornir/plugins/tasks/files/sftp.py", line 58, in compare_put_files
    dst_hash = get_dst_hash(task, dst)
  File "/usr/local/lib/python3.6/site-packages/nornir/plugins/tasks/files/sftp.py", line 29, in get_dst_hash
    result = commands.remote_command(task, command)
  File "/usr/local/lib/python3.6/site-packages/nornir/plugins/tasks/commands/remote_command.py", line 40, in remote_command
    raise CommandError(command, exit_status_code, stdout, stderr)
nornir.core.exceptions.CommandError: ('sha1sum /etc/ex.txt', 127, '', 'ash: sha1sum: not found\n')

-------------------------------------------------------------------------------------------------------------------------------

Can anyone helpme in this? Thanks.

**Comment by dbarrosop** [comment]
Hello,
I suspect you are running that task to upload files to a network device, which isn't supported by that task. You need to use `netmiko_file_transfer` in that case.

I am closing the issue but feel free to comment/reopen if you think this is not the problem.

Thanks!
