### ISSUE TITLE
extra fields not permitted (type=value_error.extra)

### ISSUE THREAD

**Issue by NetSecPy** [nornir-automation/nornir#422]
Goodday,
today i started to explore a little with nornir, 
on a machine with a a python 3.7.2 venv and Nornir 2.2.0 i receive with a very basis script, the following errors.

Traceback (most recent call last):
  File "c:\Users\Yoeri\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Yoeri\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\Yoeri\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Yoeri\OneDrive\Pyhon\nornir\nornir_sh-ver.py", line 7, in <module>
    nr = InitNornir()
  File "C:\Users\Yoeri\OneDrive\Pyhon\nornir\lib\site-packages\nornir\init_nornir.py", line 76, in InitNornir
    **conf.inventory.options,
  File "C:\Users\Yoeri\OneDrive\Pyhon\nornir\lib\site-packages\nornir\core\deserializer\inventory.py", line 129, in deserialize
    deserialized = cls(*args, **kwargs)
  File "C:\Users\Yoeri\OneDrive\Pyhon\nornir\lib\site-packages\nornir\plugins\inventory\simple.py", line 53, in __init__
    super().__init__(hosts=hosts, groups=groups, defaults=defaults, *args, **kwargs)
  File "C:\Users\Yoeri\OneDrive\Pyhon\nornir\lib\site-packages\pydantic\main.py", line 142, in __init__
    self.__setstate__(self._process_values(data))
  File "C:\Users\Yoeri\OneDrive\Pyhon\nornir\lib\site-packages\pydantic\main.py", line 312, in _process_values
    return validate_model(self, input_data)
  File "C:\Users\Yoeri\OneDrive\Pyhon\nornir\lib\site-packages\pydantic\main.py", line 474, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 6 validation errors
hosts -> R1 -> group
  extra fields not permitted (type=value_error.extra)
hosts -> R1 -> nornir_host
  extra fields not permitted (type=value_error.extra)
hosts -> R1 -> nornir_nos
  extra fields not permitted (type=value_error.extra)
hosts -> R1 -> nornir_password
  extra fields not permitted (type=value_error.extra)
hosts -> R1 -> nornir_username
  extra fields not permitted (type=value_error.extra)
hosts -> R1 -> site
  extra fields not permitted (type=value_error.extra)

i receive this, when in an interactive python session, after basic attempt to display hosts in hosts.yaml file

**Comment by ktbyers** [comment]
@NetSecPy It looks like your inventory format is using the old 1.x format.

Please make sure you update your inventory format to 2.X format. See here for an example:

https://nornir.readthedocs.io/en/stable/tutorials/intro/inventory.html


Regards, Kirk
