### ISSUE TITLE
Number of workers is seen as str

### ISSUE THREAD

**Issue by horseinthesky** [nornir-automation/nornir#426]
Hello.
I'm trying to do a simple example of function execution on two devices:
```
from nornir import InitNornir
from nornir.plugins.functions.text import print_result
from nornir.plugins.tasks.networking import netmiko_send_command

nr = InitNornir(
    config_file="config.yml", dry_run=True
)


def collect_version(task, command):
    result = task.run(netmiko_send_command, command_string=command)
    return result.result


results = nr.run(collect_version, 'show version')
print_result(results)
```

But getting an error:
```
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    results = nr.run(collect_version, 'show version')
  File "/home/horseinthesky/test/.venv/lib/python3.6/site-packages/nornir/core/__init__.py", line 133, in run
    result = self._run_parallel(task, run_on, num_workers, **kwargs)
  File "/home/horseinthesky/test/.venv/lib/python3.6/site-packages/nornir/core/__init__.py", line 66, in _run_parallel
    pool = Pool(processes=num_workers)
  File "/home/horseinthesky/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/dummy/__init__.py", line 117, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/home/horseinthesky/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/home/horseinthesky/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/pool.py", line 166, in __init__
    if processes < 1:
TypeError: '<' not supported between instances of 'str' and 'int'
```

The config file is the following:
```
---
core:
    num_workers: 10
    raise_on_error: True

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "inventory/hosts.yml"
        group_file: "inventory/groups.yml"
        defaults_file: "inventory/defaults.yml"
```

hosts.yml
```
R1:
  hostname: host1.fqdn
  groups:
    - Sasovo
  data:
    tags:
      - vrr
R2:
  hostname: host2.fqdn
  groups:
    - Vladimir
  data:
    tags:
      - vrr
```

Here are the list of packages installed in venv:
```
asn1crypto      0.24.0    
bcrypt          3.1.7     
certifi         2019.6.16 
cffi            1.12.3    
chardet         3.0.4     
colorama        0.4.1     
cryptography    2.7       
dataclasses     0.6       
future          0.17.1    
idna            2.8       
jinja2          2.10.1    
junos-eznc      2.2.1     
lxml            4.4.1     
markupsafe      1.1.1     
mypy-extensions 0.4.1     
napalm          2.4.0     
ncclient        0.6.6     
netaddr         0.7.19    
netmiko         2.4.1     
nornir          2.2.0     
nxapi-plumbing  0.5.2     
paramiko        2.6.0     
pycparser       2.19      
pydantic        0.18.2    
pyeapi          0.8.2     
pyiosxr         0.53      
pynacl          1.3.0     
pyserial        3.4       
pyyaml          5.1.2     
requests        2.22.0    
ruamel.yaml     0.15.100  
scp             0.13.2    
six             1.12.0    
textfsm         1.1.0     
urllib3         1.25.3    
```

**Comment by dbarrosop** [comment]
You need to pass kwargs:

```
nr.run(task=my_task, ....)
```

Closing this issue as I don't think this is a problem in nornir itself but feel free to reopen if you think there is.
