### ISSUE TITLE
Not able to import nornir

### ISSUE THREAD

**Issue by devangnp** [nornir-automation/nornir#458]
It gives me the following error, can you please help me with it?

<code>
In [2]: from nornir import InitNornir                                                                                                                                
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-73b0f8a04b63>", line 1, in <module>
    from nornir import InitNornir

  File "/usr/local/lib/python3.5/dist-packages/nornir/__init__.py", line 1, in <module>
    from nornir.init_nornir import InitNornir

  File "/usr/local/lib/python3.5/dist-packages/nornir/init_nornir.py", line 19
    return f"{cls.__module__}.{cls.__name__}"
                                            ^
SyntaxError: invalid syntax
</code>

<code>
root@ubuntu:~# python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nornir import InitNornir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nornir/__init__.py", line 1, in <module>
    from nornir.init_nornir import InitNornir
  File "/usr/local/lib/python3.5/dist-packages/nornir/init_nornir.py", line 19
    return f"{cls.__module__}.{cls.__name__}"
                                            ^
SyntaxError: invalid syntax
</code>

**Comment by carlmontanari** [comment]
you need py3.6+ corner uses f-strings.

**Comment by devangnp** [comment]
Thanks didn't realize the version information. pip install worked so I just went on. Thanks for help.

Upgraded pyton and its working now.
