### ISSUE TITLE
Nornir 3.0 and the expected behavior of threaded/serial options

### ISSUE THREAD

**Issue by ktbyers** [nornir-automation/nornir#554]
I had this in `config.yaml`

```yaml
runner:
  plugin: threaded
  options:
    num_workers: 10
inventory:
  plugin: SimpleInventory
  options:
    host_file: "~/nornir_inventory/hosts.yaml"
    group_file: "~/nornir_inventory/groups.yaml"
    defaults_file: "~/nornir_inventory/defaults.yaml"
```

This config.yaml file is being shared/used by multiple Python scripts. I then had one of them that I wanted to override the behavior and switch it to `serial` (for use with Pdb). 

In my Python code, I now did:

```
    nr = InitNornir(
        config_file="config.yaml",
        runner={"plugin": "serial"},
    )
```

Nornir tried to grab the `options` from config.yaml even though the `plugin` doesn't match ("threaded" vs "serial").

```
$ python exercise3c.py 
Traceback (most recent call last):
  File "exercise3c.py", line 64, in <module>
    main()
  File "exercise3c.py", line 54, in main
    runner={"plugin": "serial"},
  File "/home/kbyers/VENV/nornir_netmiko/lib64/python3.6/site-packages/nornir/init_nornir.py", line 74, in InitNornir
    runner=load_runner(config),
  File "/home/kbyers/VENV/nornir_netmiko/lib64/python3.6/site-packages/nornir/init_nornir.py", line 43, in load_runner
    runner = runner_plugin(**config.runner.options)
TypeError: __init__() got an unexpected keyword argument 'num_workers'
```

Questions:
1. Is this a behavior change from Nornir2 with respect to inline-configuration versus config.yaml? I recall that it was inline-configuration would have priority over config.yaml, but was it always a merge-behavior in Nornir2?

Let me know if that question is clear or not.

2. This behavior was unexpected to me. 

Should we switch it and make it an either-or behavior (i.e. runners is either entirely from inline-configuration or entirely from config.yaml)?

If it not either-or, I don't think the options should span different plugins. In other words, if the runner specified in config.yaml is `threaded`, then those options are not used when `serial` or any other runner is specified inline.

**Comment by ktbyers** [comment]
This works, but was very unintuitive (to me):

```python
    nr = InitNornir(
        config_file="config.yaml",
        runner={"plugin": "serial", "options": {}},
    )
```

This is after I already tried to set num_workers: 1 for `threaded` in config.yaml (which I probably shouldn't have, but lots of people are going to do--given past coding patterns in Nornir2.X).
