### ISSUE TITLE
Napalm sanitized raises TypeError: get_config() got an unexpected keyword argument 'sanitized'

### ISSUE THREAD

**Issue by Kircheneer** [nornir-automation/nornir#557]
Versions:

- Python: 3.6.9
- Nornir: 2.4.0
- Napalm: 2.5.0

config.yaml:
```
---
core:
    num_workers: 100

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "inventory/hosts.yaml"
        group_file: "inventory/groups.yaml"
        defaults_file: "inventory/defaults.yaml"
```

inventory/hosts.yml:

```
---
$REDACTED:
    hostname: $REDACTED
    port: 22
    platform: ios
```

main.py:
```
from getpass import getpass

from nornir import InitNornir
from nornir.plugins.tasks import networking
from nornir.plugins.functions.text import print_result

def nornir_set_creds(norn, username=None, password=None):
    if not username:
        username = input("Username: ")
    if not password:
        password = getpass()

    for host_obj in norn.inventory.hosts.values():
        host_obj.username = username
        host_obj.password = password

nr = InitNornir(config_file='config.yaml')
nornir_set_creds(nr)
result = nr.run(task=networking.napalm_get,
                getters=['config'],
                getters_options={'config': {'sanitized': True}})

print_result(result)

for hostname in result:
    config = result[hostname][0].result['config']['startup']
    print(config)
```

Expected behavior: Returning sanitized config file [as seen here](https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.get_config)
Actual behavior:

```
$ python main.py

Username: $REDACTED
Password:
napalm_get**********************************************************************
* $REDACTED ** changed : False *******************************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/home/$REDACTED/config_report/venv/lib/python3.6/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/$REDACTED/config_report/venv/lib/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
TypeError: get_config() got an unexpected keyword argument 'sanitized'
```

**Comment by dbarrosop** [comment]
I suspect the version of napalm you have installed doesn't support that argument. In which version was it introduced and which version are you running? could you check?

**Comment by Kircheneer** [comment]
Thanks, that was the case. For anyone else that may have that problem:

NAPALM introduces the sanitized parameter in version 3.0.
