### ISSUE TITLE
Nornir Pyqt5 Error

### ISSUE THREAD

**Issue by asoltes** [nornir-automation/nornir#580]
Hi All,

I developed a simple working script for ddos mitigation in our network using nornir, and i want to make an app with gui to make it more user friendly. but unfortunately i encounter an error "AttributeError: 'Nornir' object has no attribute 'host'. I posted already on discourse but still no reply. can somebody help me thank you.

## CODES
```
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
from networkauto import Ui_MainWindow
from ipaddress import ip_network
from datetime import datetime
from nornir import InitNornir
from nornir.plugins.tasks import networking, text
from nornir.plugins.functions.text import print_title, print_result
from nornir.plugins.tasks.networking import netmiko_send_command
import sys
import os


nr = InitNornir(config_file="config.yml",dry_run=True )

class MyWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MyWindow, self).__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

	self.ui.mitigatebtn.clicked.connect(lambda: self.ddosAutomate(nr))
	
	etc..


    def ddosAutomate(self, task):
        net = self.ui.ddos_netaddrcombobox.currentText()
        divert = self.ui.divert_chkbox.text()
        # no_divert = self.ui.nodivert_chkbox.text()
        # divert_all = self.ui.divert_all_chkbox.text()
        # no_divert_all = self.ui.no_divert_all_chkbox.text()

        r = task.run(task=text.template_file,
        mitigate=divert,
        hosts=nr.inventory.hosts,
        net=net,
        name="BGP CONFIGURATIONS",
        template="divert.j2",
        path=f"templates/{task.host}")
        task.host["config"] = r.result

    # Deploy that configuration to the device using NAPALM

        task.run(task=networking.napalm_configure,
            name="Loading Configuration on the device",
            replace=False,
            configuration=task.host["config"])

def main():
    app = QtWidgets.QApplication(sys.argv)
    w = MyWindow()
    w.show()
    sys.exit(app.exec_())
   
if __name__ == "__main__":
    main()
```

## ERROR

```
(base) C:\Users\asoltes\Desktop\pyqt-project>C:/Users/asoltes/anaconda3/python.exe c:/Users/asoltes/Desktop/pyqt-project/main.py
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Traceback (most recent call last):
  File "c:/Users/asoltes/Desktop/pyqt-project/main.py", line 57, in <lambda>
    self.ui.mitigatebtn.clicked.connect(lambda: self.ddosAutomate(nr))
  File "c:/Users/asoltes/Desktop/pyqt-project/main.py", line 249, in ddosAutomate
    path=f"templates/{task.host}")
AttributeError: 'Nornir' object has no attribute 'host'
```

I tried to do some test and create a simple template and command but another error occured.

```
r = task.run(task=text.template_file,
        mitigate=divert,
        hosts=nr.inventory.hosts,
        net=net,
        name="BGP CONFIGURATIONS",
        template="test.j2",
        path=f"templates/config_test")
```
## Error on the template test.j2 and path templates/config_test
```
Traceback (most recent call last):
  File "c:/Users/asoltes/Desktop/pyqt-project/main.py", line 57, in <lambda>
    self.ui.mitigatebtn.clicked.connect(lambda: self.ddosAutomate(nr))
  File "c:/Users/asoltes/Desktop/pyqt-project/main.py", line 243, in ddosAutomate
    r = task.run(task=text.template_file,
  File "C:\Users\asoltes\anaconda3\lib\site-packages\nornir\core\__init__.py", line 155, in run
    result = self._run_parallel(task, run_on, num_workers, **kwargs)
TypeError: _run_parallel() got multiple values for argument 'hosts'
```

**Comment by dbarrosop** [comment]
Closing as there is nothing wrong with nornir

The first issue is that you are not using nornir correctly. `self.ddosAutomate(nr)` doesn't look correct. You are passing a nornir object to a function that according to the signature should be receiving a task `def ddosAutomate(self, task):`

The second issue is that you are passing `hosts` to the `run` method which is a reserved keyword.

**Comment by asoltes** [comment]
Hi @dbarrosop ,

Got it working. Sorry for raising these kind of issue. rookie mistake :)  thanks 
```
 self.ui.mitigatebtn.clicked.connect(lambda:nr.run(task=self.ddos_automate))

```
