### ISSUE TITLE
Nornir - Big Sur

### ISSUE THREAD

**Issue by odaah** [nornir-automation/nornir#615]
I had a simple backup script (backup-script.py) for multiple vendor device environment. It was working fine before I upgraded my mac OS and failed with Big Sur. 

macOS Big Sur, 11.0.1
Python 3.8.6 

```
Traceback (most recent call last):
  File "backup-script.py", line 2, in <module>
    from nornir import InitNornir
  File "/Users/lib/python3.8/site-packages/nornir/__init__.py", line 3, in <module>
    from nornir.init_nornir import InitNornir
  File "/Users/lib/python3.8/site-packages/nornir/init_nornir.py", line 8, in <module>
    from nornir.plugins.connections.napalm import Napalm
  File "/Users/lib/python3.8/site-packages/nornir/plugins/connections/napalm.py", line 3, in <module>
    from napalm import get_network_driver
  File "/Users/lib/python3.8/site-packages/napalm/__init__.py", line 3, in <module>
    from napalm.base import get_network_driver
  File "/Users/lib/python3.8/site-packages/napalm/base/__init__.py", line 27, in <module>
    from napalm.base.base import NetworkDriver
  File "/Users/lib/python3.8/site-packages/napalm/base/base.py", line 21, in <module>
    from netmiko import ConnectHandler, NetMikoTimeoutException
  File "/Users/lib/python3.8/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/Users/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/Users/lib/python3.8/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/Users/lib/python3.8/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/Users/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/Users/lib/python3.8/site-packages/netmiko/base_connection.py", line 32, in <module>
    from netmiko.utilities import (
  File "/Users/lib/python3.8/site-packages/netmiko/utilities.py", line 9, in <module>
    import serial.tools.list_ports
  File "/Users/lib/python3.8/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/lib/python3.8/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/lib/python3.8/site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
```

Any workarounds?

**Comment by ktbyers** [comment]
I would reinstall `pyserial`. If that doesn't work I would comment out this line:

```
  File "/Users/lib/python3.8/site-packages/netmiko/utilities.py", line 9, in <module>
    import serial.tools.list_ports
```

**Comment by ktbyers** [comment]
Also which version of Netmiko are you using?


Kirk

**Comment by odaah** [comment]
Uninstalling and installing pyserial worked. I was on pyserial-3.4 and installed pyserial-3.5

```
pip3 uninstall pyserial
pip3 install pyserial
```
