### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'split'

### ISSUE THREAD

**Issue by rg0809** [nornir-automation/nornir#688]
while executing below code

```
from nornir.core import InitNornir
from nornir_utils.plugins.functions import print_result
from nornir_napalm.plugins.tasks import napalm_get

nr = InitNornir(
    config_file="config.yaml", dry_run=True
)

results = nr.run(
    task=napalm_get, getters=["facts", "interfaces"]
)
print_result(results)
```

getting error

```
/Users/ral/PycharmProjects/NWScripting/venv/lib/python3.9/site-packages/nornir/core/configuration.py:96: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "/Users/ral/PycharmProjects/NWScripting/06_Nornir_Python/test.py", line 5, in <module>
    nr = InitNornir(
  File "/Users/ral/PycharmProjects/NWScripting/venv/lib/python3.9/site-packages/nornir/core/__init__.py", line 261, in InitNornir
    conf = Config(config_file=config_file, **kwargs)
  File "/Users/ral/PycharmProjects/NWScripting/venv/lib/python3.9/site-packages/nornir/core/configuration.py", line 112, in __init__
    obj = self._resolve_import_from_string(kwargs.get(r, getattr(self, r)))
  File "/Users/ral/PycharmProjects/NWScripting/venv/lib/python3.9/site-packages/nornir/core/configuration.py", line 177, in _resolve_import_from_string
    module_name = ".".join(import_path.split(".")[:-1])
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by ubaumann** [comment]
Looks like your config.yaml is not correct. Instead of a string to describe a module you have a mapping

**Comment by dbarrosop** [comment]
I suspect there is something wrong with your environment. That exception you are getting suggest you are running nornir 2 with a configuration file for nornir 3.

**Comment by dbarrosop** [comment]
I am closing the issue as I am 90% certain that's the case but feel free to reopen otherwise.

Thanks!
