### ISSUE TITLE
Unable to pass enable secret to netmiko connection_options

### ISSUE THREAD

**Issue by erickavila888** [nornir-automation/nornir#783]
Hello. I am trying to pass an enable secret to netmiko connection_options. I'm sure its a syntax error but I can't seem to find any documentation that explicitly states how to pass an enable secret to netmiko in this fashion.

I'm able to get it working on a device that doesn't require an enable password.
```python
nr = InitNornir(config_file = 'config.yaml')
# to run this script use: "env $(gpg --decrypt inventory/encrypted.env.gpg) python3 scripts/<script>.py"
nr.inventory.defaults.username = os.getenv("SDNAC_USERNAME")
nr.inventory.defaults.password = os.getenv("SDNAC_PASSWORD")
```

Here is the code that isn't working
```python
nr = InitNornir(config_file = 'config_ap.yaml')
# to run this script use: "env $(gpg --decrypt inventory/encrypted.env.gpg) python3 scripts/<script>.py"
nr.inventory.defaults.username = os.getenv("BACKDOOR_USERNAME")
nr.inventory.defaults.password = os.getenv("BACKDOOR_PASSWORD")
nr.inventory.defaults.connection_options["netmiko"] = ConnectionOptions(
  extras={
    "secret":os.getenv("BACKDOOR_ENABLE"),
    "fast_cli":False,
    "global_delay_factor":2
  }
)
```

When I run 
```python
switch = nr.filter(F(name__contains='test_switch'))
output = switch.run(
  task = netmiko_send_command,
  command_string = 'sh ru | sec aaa',
  use_genie = True
)
```
I get this error output.
```
Traceback (most recent call last):
  File "/home/eavila/nornir3/lib64/python3.6/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/eavila/nornir3/lib64/python3.6/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 28, in netmiko_send_command
    net_connect.enable()
  File "/home/eavila/nornir3/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 25, in enable
    cmd=cmd, pattern=pattern, enable_pattern=enable_pattern, re_flags=re_flags
  File "/home/eavila/nornir3/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1699, in enable
    self.write_channel(self.normalize_cmd(self.secret))
  File "/home/eavila/nornir3/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1644, in normalize_cmd
    command = command.rstrip()
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by ktbyers** [comment]
It looks to me like this:

```
    "secret":os.getenv("BACKDOOR_ENABLE"),
```

is returning None i.e. that `BACKDOOR_ENABLE` is not set in the environment?

**Comment by dbarrosop** [comment]
I'd also suggest doing `"secret":os.getenv("BACKDOOR_ENABLE", "uh-oh"),` so you can easily see the env var isn't set and you get a string instead of `None`.

Closing as this is most likely not an issue on nornir's side but feel free to reopen otherwise.
